/* Autogenerated by /usr/bin/halcompile on Mon May  5 21:29:21 2025 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "stdio.h"
#include "rtapi_math64.h"
#include "PoKeysLibHal.h"

static int comp_id;


#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:pokeys_async:PoKeys IO driver, by Mit Zot");
MODULE_INFO(linuxcnc, "pin:in-#:bit:55:out::None:None");
MODULE_INFO(linuxcnc, "pin:ain-#:u32:3:out::None:None");
MODULE_INFO(linuxcnc, "pin:err:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:devSerial:u32:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:alive:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_bit_t *in[55];
    hal_u32_t *ain[3];
    hal_bit_t *err;
    hal_u32_t *devSerial;
    hal_bit_t *alive;

    sPoKeysDevice *dev;
};

#include <stdlib.h>
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;
static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg);
uint32_t device_id = 0;

static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    int r = 0;
    int j = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);

    r = extra_setup(inst, prefix, extra_arg);
    if (r != 0)
        return r;

    for(j=0; j < (55); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->in[j]), comp_id,
            "%s.in-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (3); j++) {
        r = hal_pin_u32_newf(HAL_OUT, &(inst->ain[j]), comp_id,
            "%s.ain-%01d", prefix, j);
        if(r != 0) return r;
    }
    r = hal_pin_bit_newf(HAL_OUT, &(inst->err), comp_id,
        "%s.err", prefix);
    if(r != 0) return r;
    r = hal_pin_u32_newf(HAL_IN, &(inst->devSerial), comp_id,
        "%s.devSerial", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->alive), comp_id,
        "%s.alive", prefix);
    if(r != 0) return r;

    r = export_rtc_pins(prefix, comp_id, inst->dev); // Export RTC pins

    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
char *names[16] = {0,};
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("pokeys_async");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "pokeys-async.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        int max_names = sizeof(names)/sizeof(names[0]);
        for(i=0; (i < max_names) && names[i]; i++) {
            if (strlen(names[i]) < 1) {
                rtapi_print_msg(RTAPI_MSG_ERR, "names[%d] is invalid (empty string)\n", i);
                r = -EINVAL;
                break;
            }
            r = export(names[i], i);
            if(r != 0) break;
       }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}
static void user_mainloop(void);

int __comp_parse_count(int *argc, char **argv) {
    int i;
    for (i = 0; i < *argc; i ++) {
        if (strncmp(argv[i], "count=", 6) == 0) {
            errno = 0;
            count = strtoul(&argv[i][6], NULL, 0);
            for (; i+1 < *argc; i ++) {
                argv[i] = argv[i+1];
            }
            argv[i] = NULL;
            (*argc)--;
            if (errno == 0) {
                return 1;
            }
        }
    }
    return 0;
}


int __comp_parse_names(int *argc, char **argv) {
    int i;
    for (i = 0; i < *argc; i ++) {
        if (strncmp(argv[i], "names=", 6) == 0) {
            char *p = &argv[i][6];
            int j;
            for (; i+1 < *argc; i ++) {
                argv[i] = argv[i+1];
            }
            argv[i] = NULL;
            (*argc)--;
            for (j = 0; j < 16; j ++) {
                names[j] = strtok(p, ",");
                p = NULL;
                if (names[j] == NULL) {
                    return 1;
                }
            }
            return 1;
        }
    }
    return 0;
}

int argc=0; char **argv=0;
int main(int argc_, char **argv_) {
    argc = argc_; argv = argv_;
    int found_count, found_names;
    found_count = __comp_parse_count(&argc, argv);
    found_names = __comp_parse_names(&argc, argv);
    if (found_count && found_names) {
        rtapi_print_msg(RTAPI_MSG_ERR, "count= and names= are mutually exclusive\n");
        return 1;
    }

    if(rtapi_app_main() < 0) return 1;
    user_mainloop();
    rtapi_app_exit();
    return 0;
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef in
#define in(i) (*(__comp_inst->in[i]))
#undef ain
#define ain(i) (*(__comp_inst->ain[i]))
#undef err
#define err (*__comp_inst->err)
#undef devSerial
#define devSerial (0+*__comp_inst->devSerial)
#undef alive
#define alive (*__comp_inst->alive)
#undef FOR_ALL_INSTS
#define FOR_ALL_INSTS() struct __comp_state *__comp_inst; for(__comp_inst = __comp_first_inst; __comp_inst; __comp_inst = __comp_inst->_next)


#include <unistd.h>   /* UNIX standard function definitions */


sPoKeysDevice * dev=0;
int i=0;
static int timeout_ms = 2000;

sPoKeysDevice *TryConnectToDevice(uint32_t intSerial) {
    rtapi_print_msg(RTAPI_MSG_DBG, "PoKeys: serial_number: %d\n", intSerial);
    rtapi_print_msg(RTAPI_MSG_DBG, "PoKeys: %s:%s: serial_number=%d\n", __FILE__, __FUNCTION__, intSerial);
    sPoKeysDevice *retDev = NULL;
    uint32_t i_Timeout = 1000;
    uint32_t enm_usb_dev = 0;
    uint32_t enm_fusb_dev = 0;
    uint32_t enm_udp_dev = 0;
    int32_t nDevs = 0;
    uint32_t lastConectionTypeTried = 0;

    if (timeout_ms > 0) {
        i_Timeout = timeout_ms;
    }
    if (intSerial != 0) {
        retDev = PK_ConnectToDevice(0); // waits for usb device
        rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: intSerial=%d\n", __FILE__, __FUNCTION__, intSerial);
        if (retDev == NULL) {
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_EnumerateUSBDevices\n", __FILE__, __FUNCTION__);
            enm_usb_dev = PK_EnumerateUSBDevices();
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: enm_usb_dev :%d\n", __FILE__, __FUNCTION__, enm_usb_dev);
            // enm_fusb_dev = PK_EnumerateFastUSBDevices();
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: enm_fusb_dev :%d\n", __FILE__, __FUNCTION__, enm_fusb_dev);
            if (enm_usb_dev != 0 || enm_fusb_dev != 0) {
                rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToDeviceWSerial(%d, %d)\n", __FILE__, __FUNCTION__, intSerial, i_Timeout);
                retDev = PK_ConnectToDeviceWSerial((uint32_t)intSerial, i_Timeout); // waits for usb device
                lastConectionTypeTried = 1;
                if (retDev == NULL) {
                    rtapi_print_msg(RTAPI_MSG_ERR,
                                    "PoKeys: %s:%s: PK_ConnectToDeviceWSerial(%d, %d) "
                                    "FAILED\n",
                                    __FILE__, __FUNCTION__, intSerial, i_Timeout);
                    retDev = PK_ConnectToDeviceWSerial((uint32_t)intSerial, i_Timeout); // waits for usb device
                    lastConectionTypeTried = 1;
                    if (retDev == NULL) {
                        rtapi_print_msg(RTAPI_MSG_ERR,
                                        "PoKeys: %s:%s: PK_ConnectToDeviceWSerial(%d, %d) "
                                        "FAILED\n",
                                        __FILE__, __FUNCTION__, intSerial, i_Timeout);

                        retDev = PK_ConnectToDeviceWSerial(intSerial, i_Timeout); // waits for usb device
                        lastConectionTypeTried = 1;
                        if (retDev == NULL) {
                            rtapi_print_msg(RTAPI_MSG_ERR,
                                            "PoKeys: %s:%s: PK_ConnectToDeviceWSerial(%d, "
                                            "%d) FAILED\n",
                                            __FILE__, __FUNCTION__, intSerial, i_Timeout);

                            retDev = PK_ConnectToDevice(0); // waits for usb device
                            lastConectionTypeTried = 1;
                            if (retDev == NULL) {
                                rtapi_print_msg(RTAPI_MSG_ERR,
                                                "PoKeys: %s:%s: PK_ConnectToDevice(0) "
                                                "FAILED\n",
                                                __FILE__, __FUNCTION__);

                                retDev = PK_ConnectToDevice(intSerial); // waits for usb device
                                lastConectionTypeTried = 1;
                                if (retDev == NULL) {
                                    rtapi_print_msg(RTAPI_MSG_ERR,
                                                    "PoKeys: %s:%s: PK_ConnectToDevice(%d) "
                                                    "FAILED\n",
                                                    __FILE__, __FUNCTION__, intSerial);
                                } else {
                                    rtapi_print_msg(RTAPI_MSG_ERR,
                                                    "PoKeys: %s:%s: PK_ConnectToDevice(%d) "
                                                    "OK\n",
                                                    __FILE__, __FUNCTION__, intSerial);
                                }

                            } else {
                                rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToDevice(0) OK\n", __FILE__, __FUNCTION__);
                            }
                        } else {
                            rtapi_print_msg(RTAPI_MSG_ERR,
                                            "PoKeys: %s:%s: PK_ConnectToDeviceWSerial(%d, "
                                            "%d) OK\n",
                                            __FILE__, __FUNCTION__, intSerial, i_Timeout);
                        }
                    } else {
                        rtapi_print_msg(RTAPI_MSG_ERR,
                                        "PoKeys: %s:%s: PK_ConnectToDeviceWSerial(%d, %d) "
                                        "OK\n",
                                        __FILE__, __FUNCTION__, intSerial, i_Timeout);
                    }

                } else {
                    rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToDeviceWSerial(%d, %d) OK\n", __FILE__, __FUNCTION__, intSerial, i_Timeout);
                }
            }
        }
        if (retDev == NULL) {
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToDeviceWSerial_UDP(%d, %d)\n", __FILE__, __FUNCTION__, intSerial, i_Timeout);
            retDev = PK_ConnectToDeviceWSerial_UDP(intSerial, i_Timeout); // waits for udp device
            if (retDev == NULL) {
                rtapi_print_msg(RTAPI_MSG_ERR,
                                "PoKeys: %s:%s: PK_ConnectToDeviceWSerial_UDP(%d, %d) "
                                "FAILED\n",
                                __FILE__, __FUNCTION__, intSerial, i_Timeout);
            } else {
                rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToDeviceWSerial_UDP(%d, %d) OK\n", __FILE__, __FUNCTION__, intSerial, i_Timeout);
            }
            lastConectionTypeTried = 2;
            rtapi_print_msg(RTAPI_MSG_DBG, "PoKeys: %s:%s: lastConectionTypeTried = 2\n", __FILE__, __FUNCTION__);
        }
        if (retDev == NULL) {
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_SearchNetworkDevices(net_devices, %d, %d)\n", __FILE__, __FUNCTION__, i_Timeout, intSerial);
            sPoKeysNetworkDeviceSummary *net_devices;
            int32_t nDevs = PK_SearchNetworkDevices(net_devices, i_Timeout, intSerial);
            if (nDevs != 0) {
                enm_udp_dev = nDevs;
                rtapi_print_msg(RTAPI_MSG_DBG, "PoKeys: %s:%s: PK_ConnectToNetworkDevice(net_devices)\n", __FILE__, __FUNCTION__);
                retDev = PK_ConnectToNetworkDevice(net_devices);
                if (retDev == NULL) {
                    rtapi_print_msg(RTAPI_MSG_ERR,
                                    "PoKeys: %s:%s: PK_ConnectToNetworkDevice(net_devices) "
                                    "FAILED\n",
                                    __FILE__, __FUNCTION__);
                } else {
                    rtapi_print_msg(RTAPI_MSG_ERR,
                                    "PoKeys: %s:%s: PK_ConnectToNetworkDevice(net_devices) "
                                    "OK\n",
                                    __FILE__, __FUNCTION__);
                }
                lastConectionTypeTried = 3;
                rtapi_print_msg(RTAPI_MSG_DBG, "PoKeys: %s:%s: lastConectionTypeTried = 3\n", __FILE__, __FUNCTION__);
            } else {
                rtapi_print_msg(RTAPI_MSG_DBG,
                                "PoKeys: %s:%s: "
                                "PK_EnumerateNetworkDevices(net_devices, %d)\n",
                                __FILE__, __FUNCTION__, i_Timeout);
                //	nDevs = PK_EnumerateNetworkDevices(net_devices, i_Timeout); // does not work - it hangs here
                // deb_out = 1135;
                if (nDevs != 0) {
                    rtapi_print_msg(RTAPI_MSG_DBG, "PoKeys: %s:%s: nDevs: %s\n", __FILE__, __FUNCTION__, nDevs);
                    enm_udp_dev = nDevs;
                    rtapi_print_msg(RTAPI_MSG_DBG,
                                    "PoKeys: %s:%s: "
                                    "PK_ConnectToNetworkDevice(net_devices)\n",
                                    __FILE__, __FUNCTION__);
                    retDev = PK_ConnectToNetworkDevice(net_devices);
                    lastConectionTypeTried = 3;
                    rtapi_print_msg(RTAPI_MSG_DBG, "PoKeys: %s:%s: lastConectionTypeTried = 3\n", __FILE__, __FUNCTION__);
                }
            }
        }
    } else {
        rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: udp_devices[16]\n", __FILE__, __FUNCTION__);
        sPoKeysNetworkDeviceSummary udp_devices[16];

        rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_EnumerateUSBDevices()\n", __FILE__, __FUNCTION__);
        enm_usb_dev = PK_EnumerateUSBDevices();
        rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_EnumerateUSBDevices()=%d\n", __FILE__, __FUNCTION__, enm_usb_dev);

        rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_EnumerateFastUSBDevices()\n", __FILE__, __FUNCTION__);
        // enm_fusb_dev = PK_EnumerateFastUSBDevices();
        // rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_EnumerateFastUSBDevices()=%d\n", __FILE__, __FUNCTION__, enm_fusb_dev);

        rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_EnumerateNetworkDevices(udp_devices, %d)\n", __FILE__, __FUNCTION__, i_Timeout);
        int32_t nDevs = PK_EnumerateNetworkDevices(udp_devices, i_Timeout); // does not work - it hangs here
        //	rtapi_print("");
        rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: nDevs: %d\n", __FILE__, __FUNCTION__, nDevs);
        // enm_udp_dev = nDevs;

        if (nDevs != 0) {
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToNetworkDevice(udp_devices) - %d\n", __FILE__, __FUNCTION__, nDevs);
            for (int i = 0; i < 16; i++) {
                if (retDev == NULL) {
                    rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: udp_devices[%d].SerialNumber: %d\n", __FILE__, __FUNCTION__, i, udp_devices[i].SerialNumber);
                    if (udp_devices[i].SerialNumber != 0) {
                        rtapi_print_msg(RTAPI_MSG_ERR,
                                        "PoKeys: %s:%s: PK_ConnectToDeviceWSerial_UDP(%d, "
                                        "%d)\n",
                                        __FILE__, __FUNCTION__, udp_devices[i].SerialNumber, i_Timeout);
                        retDev = PK_ConnectToDeviceWSerial_UDP(udp_devices[i].SerialNumber,
                                                               i_Timeout); // waits for udp device
                        lastConectionTypeTried = 2;
                        rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: lastConectionTypeTried = 2\n", __FILE__, __FUNCTION__);
                    }
                } else {
                    break;
                }
            }
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: lastConectionTypeTried = 3\n", __FILE__, __FUNCTION__);
        }
        if (enm_fusb_dev > 0) {
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToDevice FastUSB\n", __FILE__, __FUNCTION__);
            for (int i = 0; i < enm_fusb_dev + 1; i++) {
                rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToDevice(%d)\n", __FILE__, __FUNCTION__, i);
                retDev = PK_ConnectToDevice(i);
                if (retDev == NULL) {
                    rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToDevice(%d) FAILED\n", __FILE__, __FUNCTION__, i);
                } else {
                    rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToDevice(%d) OK\n", __FILE__, __FUNCTION__, i);
                }
            }
            lastConectionTypeTried = 4;
        }

        if (enm_usb_dev > 0) {
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToDevice USB\n", __FILE__, __FUNCTION__);
            for (int i = 0; i < enm_usb_dev + 1; i++) {
                rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToDevice(%d)\n", __FILE__, __FUNCTION__, i);
                retDev = PK_ConnectToDevice(i);
                if (retDev == NULL) {
                    rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToDevice(%d) FAILED\n", __FILE__, __FUNCTION__, i);
                } else {
                    rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_ConnectToDevice(%d) OK\n", __FILE__, __FUNCTION__, i);
                }
            }
            lastConectionTypeTried = 4;
        }
        // deb_out = 120;
    }
    if (retDev != NULL) {
        rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: Connected to device\n", __FILE__, __FUNCTION__);
        // connected = 1;
        if (lastConectionTypeTried == 1) {
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: USB\n", __FILE__, __FUNCTION__);
        }
        if (lastConectionTypeTried == 2) {
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: UDP\n", __FILE__, __FUNCTION__);
        }
        if (lastConectionTypeTried == 3) {
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: Network\n", __FILE__, __FUNCTION__);
        }
        return retDev;
    } else {
        rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: failed to connect to device\n", __FILE__, __FUNCTION__);
        return NULL;
    }
}


void user_mainloop(void) 
{ 
   
    while(0xb){
       FOR_ALL_INSTS() {

	 while(dev == NULL)dev = PK_ConnectToDeviceWSerial(devSerial, 2000);  //waits for usb device
	
	
	 alive=1; 
	 if ((PK_DigitalIOGet(dev) == PK_OK) && (PK_AnalogIOGet(dev) == PK_OK)){  //gets IO data and checks return value 
		err=0;
		for(i=0;i<54;i++)in(i)=!dev->Pins[i].DigitalValueGet;           //just transfers values
		for(i=0;i<3;i++)ain(i)=dev->Pins[i+44].AnalogValue;
	 }
         else{             		  //on connection error
		PK_DisconnectDevice(dev);
		dev=NULL;  		  //tries to reconnect
		err=1;
		for(i=0;i<54;i++)in(i)=0;
		for(i=0;i<3;i++)ain(i)=0;
	 }
	 alive=0;
	usleep(40000); 
        }
    }

    exit(0);
}
static int __comp_get_data_size(void) { return 0; }

EXTRA_SETUP() {
    int wait_ms = 5000;
    const char *ini_path = getenv("INI_FILE_NAME");
    FILE *fp = fopen(ini_path, "r");
    if (fp) {
        iniFindInt(fp, "DEVICE_ID", "POKEYS", &device_id);
        iniFindInt(fp, "COMM_TIMEOUT", "POKEYS", &timeout_ms);

        // ApplyIniSettings
        int tmpIniSettings = 0;
        iniFindInt(fp, "ApplyIniSettings", "POKEYS", &tmpIniSettings);

        if (tmpIniSettings != 0) {
            ApplyIniSettings = true;
        }
    }

    rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: extra_arg=%s device_id=%i \n", __FILE__, __FUNCTION__, extra_arg, device_id);

    // usleep(wait_ms);  // wait for the HAL to start up
    for (i = 0; i < retry; i++) {
        if (dev == NULL) {
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: TryConnectToDevice(0)\n", __FILE__, __FUNCTION__);
            dev = TryConnectToDevice(device_id);
        }
        if (dev != NULL) {
            rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: Connected\n", __FILE__, __FUNCTION__);
            break;
        }
    }

    if (dev == NULL) {
        rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: could not connect to device\n", __FILE__, __FUNCTION__);
    }
    //	PKEncoder_init(comp_id, dev);
    rtapi_print("");
    // devSerial = extra_arg;
    return 0;
}