/* Autogenerated by /usr/bin/halcompile on Tue Jun 10 07:55:34 2025 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:pokeys_async2:PoKeys IO driver, by Mit Zot");
MODULE_INFO(linuxcnc, "pin:in-#:bit:55:out::None:None");
MODULE_INFO(linuxcnc, "pin:ain-#:u32:3:out::None:None");
MODULE_INFO(linuxcnc, "pin:err:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:devSerial:u32:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:alive:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "funct:_:1:");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_bit_t *in[55];
    hal_u32_t *ain[3];
    hal_bit_t *err;
    hal_u32_t *devSerial;
    hal_bit_t *alive;
};
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int j = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    for(j=0; j < (55); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->in[j]), comp_id,
            "%s.in-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (3); j++) {
        r = hal_pin_u32_newf(HAL_OUT, &(inst->ain[j]), comp_id,
            "%s.ain-%01d", prefix, j);
        if(r != 0) return r;
    }
    r = hal_pin_bit_newf(HAL_OUT, &(inst->err), comp_id,
        "%s.err", prefix);
    if(r != 0) return r;
    r = hal_pin_u32_newf(HAL_IN, &(inst->devSerial), comp_id,
        "%s.devSerial", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->alive), comp_id,
        "%s.alive", prefix);
    if(r != 0) return r;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))_, inst, 1, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
RTAPI_MP_INT(count, "number of pokeys_async2");
char *names = ""; // comma separated names
RTAPI_MP_STRING(names, "names of pokeys_async2");
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("pokeys_async2");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "pokeys-async2.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        size_t i, j;
        int idx;
        char buf[HAL_NAME_LEN+1];
        const size_t length = strlen(names);
        for (i = j = idx = 0; i <= length; i++) {
            const char c = buf[j] = names[i];
            if ((c == ',') || (c == '\0')) {
                buf[j] = '\0';
                r = export(buf, idx);
                if(r != 0) {break;}
                idx++;
                j = 0;
            } else {
                if (++j == (sizeof(buf) / sizeof(buf[0]))) {
                    buf[j - 1] = '\0';
                    rtapi_print_msg(RTAPI_MSG_ERR,"names: \"%s\" too long\n", buf);
                    r = -EINVAL;
                    break;
                }
            }
        }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef in
#define in(i) (*(__comp_inst->in[i]))
#undef ain
#define ain(i) (*(__comp_inst->ain[i]))
#undef err
#define err (*__comp_inst->err)
#undef devSerial
#define devSerial (0+*__comp_inst->devSerial)
#undef alive
#define alive (*__comp_inst->alive)


#line 14 "experimental/pokeys_async2.comp"

#include <unistd.h>   /* UNIX standard function definitions */
#include "PoKeysLibHal.h"

sPoKeysDevice * dev=0;
int i=0;

void user_mainloop(void) 
{ 

   int RTC_count =10;
   int RTC_Trig = 10;
    #ifndef RTAPI
    while(0xb){
       FOR_ALL_INSTS() {

           // while(dev == NULL)dev = PK_ConnectToDeviceWSerial(devSerial, 2000);  //waits for usb device
            

            alive=1; 
            if(RTC_count>=RTC_Trig){
                rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_RTCGetAsync\n", __FILE__, __FUNCTION__);
                if (PK_RTCGetAsync(__comp_inst->dev)==0){
                    rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_RTCGetAsync OK\n", __FILE__, __FUNCTION__);
                    RTC_count = 0;
                }
                else if (PK_RTCGet(__comp_inst->dev)==PK_OK){
                    rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_RTCGet OK\n", __FILE__, __FUNCTION__);
                    RTC_count = 0;
                }
                else{
                    rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_RTCGet FAILED\n", __FILE__, __FUNCTION__);
                }
            }
            else{
                RTC_count++;
            }

            PK_ReceiveAndDispatch(__comp_inst->dev); // checks for timeout and retry
            PK_TimeoutAndRetryCheck(__comp_inst->dev, 6000); // checks for timeout and retry

            alive=0;
            usleep(100); 
        
        }
    }
    #endif
    exit(0);
}

FUNCTION(_) {
            PK_ReceiveAndDispatch(__comp_inst->dev); // checks for timeout and retry
            PK_TimeoutAndRetryCheck(__comp_inst->dev, 6000); // checks for timeout and retry

            if (PK_RTCGetAsync(__comp_inst->dev)==0){
                    rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_RTCGetAsync OK\n", __FILE__, __FUNCTION__);
                 
                }
                else if (PK_RTCGet(__comp_inst->dev)==PK_OK){
                    rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_RTCGet OK\n", __FILE__, __FUNCTION__);
                
                }
                else{
                    rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys: %s:%s: PK_RTCGet FAILED\n", __FILE__, __FUNCTION__);
                }
}
static int __comp_get_data_size(void) { return 0; }
