name: Build and Test PoKeysLib on LinuxCNC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 */14 * *'  # Run every two weeks

jobs:
  update-pokeyslib:
    runs-on: self-hosted  # Use the self-hosted LinuxCNC runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Commit and push updates
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add pokeyslib
        git commit -m "Update PoKeysLib subfolder"
        git push

  build:
    runs-on: self-hosted  # Use the self-hosted LinuxCNC runner
    needs: update-pokeyslib

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        xargs -a prerequisites.txt sudo apt-get install -y

    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Build PoKeysLib
      run: |
        mkdir build && cd build
        cmake ..
        make
      continue-on-error: true  # Continue to next steps even if the build fails

    - name: Save build logs
      run: |
        if [ -f build.log]; then
          cat build.log
        fi
      if: failure()

    - name: Create GitHub Issue on Failure
      if: failure()
      run: |
        echo "Build failed, attaching logs."
        LOG_FILE="build.log"
        if [ -f $LOG_FILE]; then
          gh issue create --title "Build Error: ${{ github.sha }}" --body-file $LOG_FILE --label "build-error" --assignee @your-username
        else
          echo "No build log found."

    - name: Build PoKeysLib for Linux
      run: |
        cd pokeyslib
        mkdir build && cd build
        cmake ..
        make
