name: Build and Test PoKeysLib on LinuxCNC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 */14 * *'  # Run every two weeks

jobs:
  update-pokeyslib:
    runs-on: self-hosted  # Use the self-hosted LinuxCNC runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update submodules
      run: git submodule update --remote --recursive

    - name: Commit and push updates if needed
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Check if there are changes
        if git status --porcelain | grep .; then
          git add .
          git submodule foreach git add .
          git commit -m "Update PoKeysLib submodule"
          git push
        else
          echo "No changes to commit."
        fi

  build:
    runs-on: self-hosted 
    needs: update-pokeyslib

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        xargs -a prerequisites.txt sudo apt-get install -y

    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Build PoKeysLib
      run: |
        mkdir build && cd build
        cmake ..
        make
      continue-on-error: true

    - name: Save build logs on failure
      if: failure()
      run: |
        if [ -f build.log ]; then
          cat build.log
        fi

    - name: Create GitHub Issue on failure
      if: failure()
      run: |
        if [ -f build.log ]; then
          gh issue create --title "Build Error: ${{ github.sha }}" --body-file build.log --label build-error
        else
          echo "No build log found."
        fi

    - name: Build PoKeysLib for Linux
      run: |
        cd pokeyslib
        mkdir -p build && cd build
        cmake ..
        make

    - name: Sync repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Sync repository"
        git push

    - name: Get Git version info
      run: git version

    - name: Copy .gitconfig if exists
      run: |
        if [ -f "${HOME}/.gitconfig" ]; then
          cp "${HOME}/.gitconfig" "${GITHUB_WORKSPACE}/../_temp/gitconfig"
        else
          echo "No .gitconfig found, skipping copy."
        fi

    - name: Override HOME
      run: export HOME=/home/zarfld/actions-runner2/_work/_temp/e57545ec-8da1-4ecc-86a7-d75576d1a366

    - name: Add safe directory
      run: git config --global --add safe.directory /home/zarfld/actions-runner2/_work/pokeyslib-fork/pokeyslib-fork

    - name: Get remote.origin.url
      run: git config --local --get remote.origin.url

    - name: Remove refs
      run: git update-ref -d refs/heads/main

    - name: Clean repository
      run: git clean -fdx

    - name: Disable garbage collection
      run: git config --global gc.auto 0

    - name: Set up auth
      run: |
        echo "Setting up auth"
        git config --local --name-only --get-regexp core\.sshCommand
        git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
        if [ $? -ne 0 ]; then
          echo "Error: Missing URL for submodule path 'pokeyslib' in .gitmodules"
          exit 1
        fi
        echo "Auth setup complete"

    - name: Log .gitmodules file
      run: |
        echo "Logging .gitmodules file"
        cat .gitmodules
        echo "Logging complete"

    - name: Temporarily override HOME
      run: export HOME=/home/zarfld/actions-runner2/_work/_temp/1b4ae179-fc69-433d-ba3a-3ec87d24903c